### PR TITLE
Create lidya

### PR DESCRIPTION
**Pull request by basedtho**
Hope this doesn't break anything and I didn't do anything wrong

### CODE REVIEW

**Comment by basedtho** [comment]
Oh :(

**Comment by zackify** [comment]
Same problem here, Cname needs to be the root of a domain, check how my existing one is setup

**Comment by basedtho** [comment]
I fixed it! Thank you!

**Comment by basedtho** [comment]
Oh, how do I configure the redirect :(

I have these lines in my nginx config

```
server {
  server_name lidya.b0x.me;
  rewrite / https://git.sr.ht/~tho/lidya permanent;
}
```

But it doesn't work!

**Comment by zackify** [comment]
I should add an faq :)

You need to make sure that lidya.box.me points to your servers IP address (pretty sure that is correct right now)

Then you would add another server_name, so make a new site in your sites-enabled folder.

The server_name would be “lidya.cli.rs”

**Comment by basedtho** [comment]
I've added the site! Here's what's inside
```
server {
  server_name lidya.cli.rs
  rewrite / https://git.sr.ht/~tho/lidya
}
```
But it still doesn't work. And it points to some ip address I don't know

**Comment by zackify** [comment]
Looks like you have it redirecting, I just went to it!

**Comment by basedtho** [comment]
Yeah, it works now, but https://i.imgur.com/Q4IZL3U.png :(

**Comment by basedtho** [comment]
You fixed it yay! Thank you

**Pull request merged**
