### PR TITLE
Create discord_presence

### PR DESCRIPTION
**Pull request by Tofix26**

### CODE REVIEW

**Comment by zackify** [comment]
The value for your domain is not a valid cname. Please check the other files in the repo and look up cname records. Then I can merge after you fix it.

**Comment by Tofix26** [comment]
Ok fixed

**Comment by zackify** [comment]
I’m pretty sure you need to add the domain this way for vercel. You can’t point it to the vercel url, add it here and put the value they give in project settings: https://vercel.com/docs/concepts/projects/custom-domains

**Comment by Tofix26** [comment]
Ok i just switched to gh-pages

**Pull request closed without merging**
