### PR TITLE
Create database

### PR DESCRIPTION
**Pull request by fel1x0u**
Not exactly for rust, but I like coding!

### CODE REVIEW

**Comment by AcaiBerii** [comment]
Some advice to link this properly, you can follow my interactive tutorial for more help:

tutorial

**Comment by fel1x0u** [comment]
That should be better.

**Comment by zackify** [comment]
If this isn't rust related why are you wanting to use this domain?

**Comment by AcaiBerii** [comment]
> If this isn't rust related why are you wanting to use this domain?

Are we not allowed to use this domain if it's not rust related?  
None of my PRs are being accepted in any other subdomain repository.

**Comment by UltiRequiem** [comment]
I think we should close this issue and specify more clearly in the readme this is only for Rust Projects 🦀

**Comment by UltiRequiem** [comment]
> I think we should close

With #30 , can this be closed?

**Pull request closed without merging**
