### PR TITLE
Create wte

### PR DESCRIPTION
**Pull request by BlackPhlox**
Thanks Zach! 👍

### CODE REVIEW

**Comment by BlackPhlox** [comment]
Seems like there is an issue with the token for adding a CNAME using the Digital Ocean workflow.

**Comment by zackify** [comment]
Ahh, guess I will need to turn off on PR and wait until I merge then. Good points.

**Comment by zackify** [comment]
You can’t have a “slash” in a cname so this failed

**Comment by BlackPhlox** [comment]
I kind of forgot aswell that DNS records only map IP addresses to hostnames😅 I would just have to handle it on my server when a request comes from your domain.

**Pull request merged**
